language: node_js
before_script:
  - npm install codecov -g
  - corepack enable
  - yarn init -2
sudo: false
node_js:
  - 18
install:
  - yarn install
script:
  - yarn test
  - codecov -f coverage/*.json